### ISSUE TITLE
USER STORY: Manage a poll

### ISSUE THREAD

**Issue by JosLaw** [JosLaw/CI-Template#5]
In order to automatically hide the poll as an administrator, I can pick the expiry date while publishing the poll

## Acceptance criteria:
 - The poll should disappear at 11:59pm on the target date
 - The real estate of the poll should be reserved on the home page. A message saying "New poll coming soon" should display if no active poll present
 - The administrator expiry should be at least 3 days after the current date

## Tasks:
 - [ ] Update the admin module view: the poll design (HTML & CSS) to include date picker
 - [ ] Update the website view: show  "New poll coming soon"
 - [ ] Create a Javascript function to validate that the date is at least after 3 days
 - [ ] Create a job to check expired polls everyday at 11:59pm and hide them
 - [ ] Update the controller function
 - [ ] Update unit test scripts
 - [ ] Test the functionality
